// this-or-that/prompts.js
// 140+ fresh curated pairs across Lifestyle, Food, Romance, Travel, Entertainment, and more

const THIS_OR_THAT_PROMPTS = [
  // --- Lifestyle & Habits ---
  { optionA: "Phone on Silent Always 🔕", optionB: "Ringtone & Vibrations On 🔔" },
  { optionA: "Read Physical Paperbacks 📚", optionB: "Read on an E-Reader / Kindle 📱" },
  { optionA: "Early Dinner at 6 PM 🍽️", optionB: "Late Dinner at 10 PM 🌙" },
  { optionA: "Zero Unread Emails 📬", optionB: "9,999+ Unread Badges 📩" },
  { optionA: "Sunday Reset & Meal Prep 🥗", optionB: "Lazy Sunday in Bed 🛌" },
  { optionA: "Coffee First Thing ☕", optionB: "Big Glass of Water First 🧊" },
  { optionA: "Paper Planner & Journal 📓", optionB: "Digital Calendar & Notes 📲" },
  { optionA: "Work Out in the Morning 🌅", optionB: "Work Out at Night 🌃" },
  { optionA: "Talk to Friendly Strangers 👋", optionB: "Avoid Eye Contact at All Costs 🕶️" },
  { optionA: "Keep Souvenirs & Trinkets 🧸", optionB: "Declutter Everything Ruthlessly 🗑️" },
  { optionA: "Live in a Busy Megacity 🏙️", optionB: "Live in a Sleepy Coastal Town 🌊" },
  { optionA: "Ride Public Transit 🚆", optionB: "Drive Everywhere Alone 🚗" },
  { optionA: "One Alarm with Snooze ⏰", optionB: "Five Separate Alarms 🚨" },
  { optionA: "Sleep in Pure Darkness 🌑", optionB: "Sleep with a Nightlight or TV 💡" },

  // --- Food & Drinks ---
  { optionA: "Crispy Thin Crust Pizza 🍕", optionB: "Deep-Dish Cheesy Pizza 🧀" },
  { optionA: "Fresh Bakery Pastries 🥐", optionB: "Hearty Breakfast Burrito 🌯" },
  { optionA: "Dip Fries in Milkshake 🥤", optionB: "Classic Ketchup Only 🍅" },
  { optionA: "Homemade Fruit Smoothie 🍓", optionB: "Fresh Pressed Green Juice 🥒" },
  { optionA: "Sweet Maple Syrup Pancakes 🥞", optionB: "Savory Bacon & Egg Toast 🍳" },
  { optionA: "Spicy Garlic Wings 🍗", optionB: "Sweet Tangy BBQ Ribs 🍖" },
  { optionA: "Warm Cinnamon Rolls 🥮", optionB: "Fresh Glazed Donuts 🍩" },
  { optionA: "Hot Pot Feast 🍲", optionB: "Korean BBQ Grilling 🥩" },
  { optionA: "Crunchy Tortilla Chips & Salsa 🌶️", optionB: "Warm Pita & Creamy Hummus 🫓" },
  { optionA: "Sour Tangy Candy 🍋", optionB: "Sweet Milk Chocolate 🍫" },
  { optionA: "Fizzy Soda / Pop 🥤", optionB: "Iced Fruit Tea 🧋" },
  { optionA: "Soft-Serve Cone 🍦", optionB: "Artisan Gelato Cup 🍨" },
  { optionA: "Eat with Chopsticks 🥢", optionB: "Eat with Fork & Spoon 🍴" },
  { optionA: "Loaded Cheeseburger 🍔", optionB: "Crispy Fish Tacos 🌮" },

  // --- Romance & Couple Life ---
  { optionA: "Matching Phone Wallpapers 📱", optionB: "Keeping Default Backgrounds 🖼️" },
  { optionA: "Playful Play-Fights & Tickling 🤼", optionB: "Gentle Head Scratches & Massages 💆" },
  { optionA: "Spontaneous 2 AM Road Trip 🚗", optionB: "Planned Fancy Candlelit Dinner 🕯️" },
  { optionA: "Share Every Single Thought 🗣️", optionB: "Comfortable Silence Side-by-Side 🤫" },
  { optionA: "Steal the Blanket at Night 🛌", optionB: "Sleep Back-to-Back for Space ❄️" },
  { optionA: "Co-op Video Game Date 🎮", optionB: "Bake a Messy Cake Together 🎂" },
  { optionA: "Handmade Playlist for Each Other 🎵", optionB: "Curated Box of Favorite Snacks 🍫" },
  { optionA: "Soft Cheek & Nose Kisses 😚", optionB: "Back Hugs Out of Nowhere 🫂" },
  { optionA: "Write Long Love Letters 💌", optionB: "Send 50 Memes a Day 🤳" },
  { optionA: "Wear Their Oversized Hoodie 🧥", optionB: "Borrow Their Favorite Perfume/Cologne ✨" },
  { optionA: "Double Dates with Friends 👥", optionB: "Just the Two of Us Always 🔒" },
  { optionA: "Remember Exact Anniversaries 🗓️", optionB: "Celebrate Random Everyday Wins 🎉" },
  { optionA: "Cook Together with Music 🍳", optionB: "Order Takeout & Build a Pillow Fort 🏰" },

  // --- Travel & Adventures ---
  { optionA: "Hike Active Volcanic Trails 🌋", optionB: "Scuba Dive Coral Reefs 🤿" },
  { optionA: "Sleeper Train Across the Country 🚆", optionB: "Direct Non-Stop Flight ✈️" },
  { optionA: "Stay in a Treehouse Resort 🌲", optionB: "Stay in an Underwater Hotel 🐠" },
  { optionA: "Visit Frozen Arctic Fjords 🧊", optionB: "Explore Ancient Desert Ruins 🏜️" },
  { optionA: "Carry-On Only Efficiency 🧳", optionB: "Check Two Huge Suitcases 🛍️" },
  { optionA: "Eat Exclusively Street Stalls 🍢", optionB: "Book Michelin-Starred Spots 🍽️" },
  { optionA: "Solo Travel Adventure 🧭", optionB: "Group Trip with Best Friends 👯" },
  { optionA: "Explore Cities on Foot 👟", optionB: "Hop-On Hop-Off Tour Bus 🚌" },
  { optionA: "Wake Up for Golden Hour Sunrises 🌄", optionB: "Stay Out for Vibrant Nightlife 🪩" },
  { optionA: "Rent a Camper Van 🚐", optionB: "Book Boutique Airbnb Lofts 🏡" },
  { optionA: "Paper Map & Compass Navigation 🗺️", optionB: "Google Maps Saved Pins 📍" },
  { optionA: "Return to the Same Favorite Spot 🔁", optionB: "Never Visit the Same Place Twice 🌍" },

  // --- Entertainment & Media ---
  { optionA: "Mind-Bending Psychological Thrillers 🧠", optionB: "Comfort Feel-Good Sitcoms 🛋️" },
  { optionA: "Fast-Paced Competitive Shooters 🎯", optionB: "Cozy Farming Simulators 🌾" },
  { optionA: "Massive Stadium Music Festivals 🎪", optionB: "Acoustic Coffeehouse Gigs 🎸" },
  { optionA: "Read the Manga / Light Novel First 📖", optionB: "Wait for the Anime Adaptation 📺" },
  { optionA: "Rewatch Childhood Nostalgia Movies 📼", optionB: "Always Watch Latest Releases 🎬" },
  { optionA: "Deep Lore High Fantasy 🧙‍♂️", optionB: "Gritty Dystopian Sci-Fi 🤖" },
  { optionA: "Physical Vinyl Records 🎶", optionB: "Spotify Algorithmic Radio 🎧" },
  { optionA: "Single-Player Story Mode 🗡️", optionB: "Multiplayer Co-Op Mayhem 🕹️" },
  { optionA: "Stand-Up Comedy Special 🎙️", optionB: "Broadway Musical Theater 🎭" },
  { optionA: "Mystery Escape Room Challenge 🗝️", optionB: "Arcade Claw Machine & Skee-Ball 🎟️" },
  { optionA: "Read Graphic Novels / Webtoons 🎨", optionB: "Read Dense Fiction Novels 📚" },
  { optionA: "Watch With Subtitles Always 💬", optionB: "Pure Audio Without Subtitles 🔊" },

  // --- Aesthetics & Vibe ---
  { optionA: "Clean Scandinavian Minimalism 🤍", optionB: "Boho Maximalism with Clutter 🏺" },
  { optionA: "Warm Amber Desk Lamps 💡", optionB: "Vibrant RGB Backlighting 🌈" },
  { optionA: "All-Black Monochromatic Wardrobe 🖤", optionB: "Eclectic Bold Colors & Prints 🎨" },
  { optionA: "Oversized Knit Sweaters 🧶", optionB: "Structured Tailored Blazers 🧥" },
  { optionA: "Classic Film Grain Photography 🎞️", optionB: "Ultra-Sharp 4K Crisp Visuals 📷" },
  { optionA: "Earthy Forest Green Tones 🌲", optionB: "Moody Midnight Ocean Blues 🌊" },
  { optionA: "Chunky Platform Boots 🥾", optionB: "Retro White Canvas Sneakers 👟" },
  { optionA: "Handmade Clay Pottery 🏺", optionB: "Brushed Industrial Stainless Steel ⚙️" },
  { optionA: "Steampunk Brass & Gears 🕰️", optionB: "Synthwave Chrome & Neon 🌆" },
  { optionA: "Vintage Thrifted Treasures 🏷️", optionB: "Crisp Modern Designer Drops ✨" },

  // --- Home & Decor ---
  { optionA: "Floor-to-Ceiling Bookshelves 📚", optionB: "Massive Art Gallery Wall 🖼️" },
  { optionA: "Cozy Built-In Window Nook 🪟", optionB: "Sprawling Outdoor Balcony 🌿" },
  { optionA: "Plush Velvet Sectional Sofa 🛋️", optionB: "Classic Leather Armchairs 🪑" },
  { optionA: "Heated Bathroom Floors ♨️", optionB: "Towel Warmer Rack 🧖" },
  { optionA: "Traditional Wood Fireplace 🔥", optionB: "Modern Electric Floating Hearth ⚡" },
  { optionA: "Kitchen Island with Bar Stools 🍷", optionB: "Big Farmhouse Wooden Dining Table 🥖" },
  { optionA: "Fluffy Down Feather Duvet 🪶", optionB: "Heavy Weighted Blanket 💤" },
  { optionA: "Skylight Above the Bed 🌌", optionB: "Blackout Curtains All Day 🌑" },
  { optionA: "Dedicated Home Office 🖥️", optionB: "Dedicated Hobby / Gaming Room 🎮" },
  { optionA: "Herb Garden on Windowsill 🌿", optionB: "Fresh Cut Flower Vases Weekly 💐" },

  // --- Seasons & Weather ---
  { optionA: "Dense Foggy Morning 🌫️", optionB: "Crisp Sunny Sub-Zero Morning ❄️" },
  { optionA: "Warm Gentle Summer Drizzle 🌦️", optionB: "Pouring Torrential Rainstorm ⛈️" },
  { optionA: "Golden Autumn Sunsets 🌇", optionB: "Bright Spring Sunrise 🌅" },
  { optionA: "Walking Barefoot in Grass 🌱", optionB: "Walking Barefoot in Beach Sand 🏖️" },
  { optionA: "Wool Scarves & Beanies 🧣", optionB: "Cool Linen Shirts & Shades 🕶️" },
  { optionA: "Thunder Rolling in the Distance ⚡", optionB: "Sound of Crickets on a Summer Night 🦗" },
  { optionA: "Ice Skating on a Frozen Pond ⛸️", optionB: "Swimming in a Natural River 🏊" },
  { optionA: "Warm Cinnamon Apple Cider 🍎", optionB: "Cold Watermelon Slices in the Sun 🍉" },
  { optionA: "Cozy Woolen Mittens 🧤", optionB: "Breezy Flip-Flops 🩴" },
  { optionA: "Watching Snow Fall Indoors ☕", optionB: "Sitting by a Campfire Outdoors 🪵" },

  // --- Deep & Thoughtful ---
  { optionA: "Speak Every Spoken Language 🗣️", optionB: "Talk to and Understand Animals 🐾" },
  { optionA: "Freeze Time for 1 Hour Daily ⏸️", optionB: "Rewind Time by 10 Seconds Anytime ⏪" },
  { optionA: "Explore the Deepest Ocean Trench 🌊", optionB: "Walk on the Surface of Mars 🔴" },
  { optionA: "Photographic Memory Forever 🧠", optionB: "Ability to Forget Painful Memories ✨" },
  { optionA: "Know Every Mystery of the Universe 🌌", optionB: "Live a Simple, Blissfully Happy Life 🌻" },
  { optionA: "Never Need to Sleep Again ⚡", optionB: "Fall Asleep in 30 Seconds Anywhere 😴" },
  { optionA: "Have Absolute Creative Genius 🎨", optionB: "Have Absolute Logical Intellect 🧩" },
  { optionA: "Know the Year You Will Die ⏳", optionB: "Know How You Will Die 🛑" },
  { optionA: "Be Remembered for Centuries 🏛️", optionB: "Be Deeply Cherished by a Few Now 🤍" },
  { optionA: "Live Without Digital Devices 📵", optionB: "Live Without Music Forever 🔇" },

  // --- Work & Social Life ---
  { optionA: "Four 10-Hour Workdays 🗓️", optionB: "Five 6-Hour Workdays ⏰" },
  { optionA: "Present to a Room of 500 People 🎤", optionB: "Have a Difficult 1-on-1 Performance Review 👔" },
  { optionA: "Collaborative Open Studio 🗣️", optionB: "Private Quiet Office with a Door 🚪" },
  { optionA: "Work Early Morning (6 AM - 2 PM) 🌅", optionB: "Work Night Shift (4 PM - Midnight) 🌃" },
  { optionA: "Plan Outing Weeks Ahead 📅", optionB: "'You Free in 15 Minutes?' Spontaneity 🏃" },
  { optionA: "Reply to Messages in 2 Seconds ⚡", optionB: "Reply After 3 Business Days 🐢" },
  { optionA: "Meet Friends at Cozy Cafes ☕", optionB: "Meet Friends for Outdoor Activities 🚴" },
  { optionA: "Work in a Standing Desk 🧍", optionB: "Work Reclined in a Bean Bag 🛋️" },
  { optionA: "Small High-School Reunion 🎓", optionB: "Meeting Completely New Strangers 🌐" },
  { optionA: "Be the Designated Driver 🚗", optionB: "Be the Route Navigator / DJ 🎶" },

  // --- Silly & Chaotic ---
  { optionA: "Every Dog You Pass Judges You Silently 🐕", optionB: "Every Cat You Pass Yells Insults at You 🐈" },
  { optionA: "Hands Made of Foam Fingers 🧤", optionB: "Feet Made of Flippers 🤿" },
  { optionA: "Must Sing Everything Instead of Speaking 🎤", optionB: "Must Moonwalk Everywhere You Walk 🕺" },
  { optionA: "Sweat Pure Lemonade 🍋", optionB: "Cry Maple Syrup 🥞" },
  { optionA: "Have Involuntary Dramatic Theme Music 🎺", optionB: "Have a Studio Laugh Track After Every Joke 🎭" },
  { optionA: "Fight 50 Pigeon-Sized Geese 🪿", optionB: "Fight 1 Goose-Sized Pigeon 🐦" },
  { optionA: "Always Smell Slightly of Popcorn 🍿", optionB: "Always Smell Slightly of Fresh Cookies 🍪" },
  { optionA: "Your Life Narrated by Morgan Freeman 🎙️", optionB: "Your Life Narrated by Gordon Ramsay 🍳" },
  { optionA: "Sneeze Every Time Someone Says Hello 🤧", optionB: "Hiccup Every Time You Tell a Lie 🦹" },
  { optionA: "Wear a Winter Coat in Summer Heat 🧥", optionB: "Wear a Swimsuit in Winter Snow 🩱" }
];